Updating Spanish translations
aspirepress/AspireUpdate pull request #150
Opened 2024-11-07 13:07 UTC by davefx

# Pull Request

## What changed?

Added missing strings

## Why did it change?

(Please list the reasons you made the changes...)

## Did you fix any specific issues?

(Please tag any specific issues here...)

## CERTIFICATION

By opening this pull request, I do agree to abide by
the [CODE OF CONDUCT](https://github.com/aspirepress/.github/CODE_OF_CONDUCT.md) and be bound by the terms
of the [Contribution Guidelines](https://github.com/aspirepress/.github/CONTRIBUTING.md) in effect on the date and time
of my contribution as proven by the
revision information in GitHub. I also agree that any previous contributions shall be deemed subject to the terms of the
version in effect on the date and time of this pull request, or any future revisions for pull requests I may submit.
Further, I certify that this work is my own, is original, does not violate the intellectual property of any other person
or entity, and I am not violating any license agreements or contracts I have with any person or entity. Finally, I agree
that this code may be licensed under any license deemed appropraite by AspirePress, including but not
limited to open source, closed source, proprietary or custom licenses, and that such license terms neither violate my
rights or my copyright to this code.

2024-11-07 13:58 UTC, ipajen approved these changes

2024-11-07 13:59 UTC, ipajen approved these changes

2024-11-07 15:55 UTC, juanlopez4691 requested changes

2024-11-07 15:55 UTC, juanlopez4691 commented on languages/AspireUpdate-es_ES.po
> +msgstr "Tus actualizaciones de plugins ahora funcionan con <strong>%1$s</strong>. <a href=\"%2$s\">Leer más</a> "
```suggestion
msgstr "La actualización de tus plugins ahora funciona con <strong>%1$s</strong>. <a href=\"%2$s\">Leer más</a> "
```

2024-11-07 15:55 UTC, juanlopez4691 commented on languages/AspireUpdate-es_ES.po
> +msgstr "Tus actualizaciones de temas ahora funcionan con <strong>%1$s</strong>. <a href=\"%2$s\">Leer más</a>"
```suggestion
msgstr "La actualización de tus temas ahora funciona con <strong>%1$s</strong>. <a href=\"%2$s\">Leer más</a>"
```

2024-11-07 15:55 UTC, juanlopez4691 commented on languages/AspireUpdate-es_ES.po
> +msgstr "Tus actualizaciones de WordPress, plugins, temas y traducciones ahora funcionan con <strong>%1$s</strong>. <a href=\"%2$s\">Leer más</a>"
```suggestion
msgstr "La actualización de WordPress, plugins, temas y traducciones ahora funciona con <strong>%1$s</strong>. <a href=\"%2$s\">Leer más</a>"
```

2024-11-07 19:35 UTC, ipajen approved these changes

2024-11-07 22:56 UTC, ipajen approved these changes

2024-11-08 06:38 UTC, ipajen approved these changes

2024-11-08 09:49 UTC, merged