Issue Fixes
aspirepress/AspireUpdate pull request #61
Opened 2024-10-28 14:39 UTC by namithj

# Pull Request

## What changed?

[#56](https://github.com/aspirepress/AspireUpdate/issues/56)
[#47](https://github.com/aspirepress/AspireUpdate/issues/47)
[#43](https://github.com/aspirepress/AspireUpdate/issues/43)
[#42](https://github.com/aspirepress/AspireUpdate/issues/42)
[#41](https://github.com/aspirepress/AspireUpdate/issues/41)

## Why did it change?

Issues Fixed

## Did you fix any specific issues?

[#56](https://github.com/aspirepress/AspireUpdate/issues/56)
[#47](https://github.com/aspirepress/AspireUpdate/issues/47)
[#43](https://github.com/aspirepress/AspireUpdate/issues/43)
[#42](https://github.com/aspirepress/AspireUpdate/issues/42)
[#41](https://github.com/aspirepress/AspireUpdate/issues/41)

## CERTIFICATION

By opening this pull request, I do agree to abide by
the [CODE OF CONDUCT](https://github.com/aspirepress/.github/CODE_OF_CONDUCT.md) and be bound by the terms
of the [Contribution Guidelines](https://github.com/aspirepress/.github/CONTRIBUTING.md) in effect on the date and time
of my contribution as proven by the
revision information in GitHub. I also agree that any previous contributions shall be deemed subject to the terms of the
version in effect on the date and time of this pull request, or any future revisions for pull requests I may submit.
Further, I certify that this work is my own, is original, does not violate the intellectual property of any other person
or entity, and I am not violating any license agreements or contracts I have with any person or entity. Finally, I agree
that this code may be licensed under any license deemed appropraite by AspirePress, including but not
limited to open source, closed source, proprietary or custom licenses, and that such license terms neither violate my
rights or my copyright to this code.

2024-10-28 14:46 UTC, asirota requested changes
Check the error message language for WordPress_filesystem

2024-10-28 14:46 UTC, asirota commented on includes/class-debug.php
Would be nicer to have more friendly error comment such as

"Could not open or write to the host file system."

2024-10-28 14:49 UTC, asirota commented
@namithj can you add 

`Closes: `

Prefix before each issue number link in the fixed section.

2024-10-28 15:56 UTC, namithj commented on includes/class-debug.php
Can we use something else in place of Hosts.  We are already using Host as in the API Host.

2024-10-28 20:03 UTC, namithj commented on includes/class-debug.php
Added to file

2024-10-28 20:47 UTC, asirota approved these changes

2024-10-28 20:47 UTC, merged

2024-10-29 01:31 UTC, costdev commented
Reviewing is much harder for contributors when they have to learn and follow multiple contexts.

Is it okay if we avoid solving multiple unrelated issues in one PR?

2024-10-29 02:35 UTC, asirota commented
So then one issue and one pr per issue? @namithj what do you think of that?

2024-10-29 02:37 UTC, asirota reviewed
Looks good

2024-10-29 03:00 UTC, namithj commented
It's alright for me.  This is more of a time saving measure since we only have 6-7 files in the plugin to take care of

2024-10-29 03:07 UTC, asirota commented
Let's try to make the Pr more atomic to one or two related issues tougher then.